# This is a basic workflow to help you get started with Actions
name: CI

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [main]
# It seems this CI runs twice when a pull_request is merged. It should only run once on the push.
# Another CI that would run when a pull_request is submitted but before it is merged would be nice.
# But, I'd want it to push to a different environment, not my production server as it is doing now!
#  pull_request:
#    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Upload public dir
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
        env:
          CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download public dir
        uses: actions/download-artifact@v4.1.7
        with:
          name: public
          path: public
      - name: 📂 Sync files over FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}          
          local-dir: ./public/
          server-dir: ./      
